name = "telegram-openrouter-bot" # Replace with your desired worker name
main = "worker.js"
compatibility_date = "2024-03-20" # Update to a recent date

# Environment variables for secrets and configuration
# These should be set in your Cloudflare dashboard (Settings > Variables)
# or via `wrangler secret put <VARIABLE_NAME>`
# NEVER commit secrets directly into this file or your repository!
[vars]
 ALLOWED_USER_IDS = "6976475679,1540050779" # Comma-separated list of allowed Telegram User IDs
 DEFAULT_LANGUAGE = "en" # or "id"
 DEFAULT_MODEL = "deepseek/deepseek-chat-v3-0324:free" # Default OpenRouter model identifier
 DEFAULT_SYSTEM_PROMPT = "You are a helpful assistant."
 TELEGRAM_BOT_TOKEN = "7865447002:AAFFgAn2XlfZttjyhHanfN27Nv-meplGUq0" # Your Telegram Bot Token
 OPENROUTER_API_KEY = "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" # Optional: Your own OpenRouter key if the bot needs to make admin calls (e.g., fetch all models dynamically) - User keys are stored in KV
 GOOGLE_API_KEY = "AIzaSyCgfxjkYsGTAkvhJHuMWoboWfYbeBiElvk" # Google Custom Search API Key (Needed for web search)
 GOOGLE_CX = "b65890f056f634ae9" # Google Custom Search Engine ID (Needed for web search)
# BING_API_KEY = "" # Bing Search API Key (Needed for fallback search)

# KV Namespace Bindings
# Create KV namespaces in your Cloudflare dashboard (Workers & Pages > KV)
# and add the bindings here. Replace the placeholder IDs.

[[kv_namespaces]]
binding = "USER_DATA" # Name used to access the KV namespace in the worker code
id = "<your_user_data_kv_namespace_id>" # The ID of your USER_DATA KV namespace
preview_id = "<your_user_data_kv_namespace_preview_id>" # The Preview ID of your USER_DATA KV namespace

[[kv_namespaces]]
binding = "CACHE" # Name used for caching search results
id = "<your_cache_kv_namespace_id>" # The ID of your CACHE KV namespace
preview_id = "<your_cache_kv_namespace_preview_id>" # The Preview ID of your CACHE KV namespace
