name = "telegram-openrouter-bot" # Replace with your desired worker name
main = "worker.js"
compatibility_date = "2024-03-20" # Update to a recent date

# Environment variables for secrets and configuration
# These should be set in your Cloudflare dashboard (Settings > Variables)
# or via `wrangler secret put <VARIABLE_NAME>`
# NEVER commit secrets directly into this file or your repository!
[vars]
# ALLOWED_USER_IDS = "ID1,ID2,ID3" # Comma-separated list of allowed Telegram User IDs
# DEFAULT_LANGUAGE = "en" # or "id"
# DEFAULT_MODEL = "openai/gpt-3.5-turbo" # Default OpenRouter model identifier
# DEFAULT_SYSTEM_PROMPT = "You are a helpful assistant."

[secrets]
# TELEGRAM_BOT_TOKEN = "" # Your Telegram Bot Token
# OPENROUTER_API_KEY = "" # Optional: Your own OpenRouter key if the bot needs to make admin calls (e.g., fetch all models dynamically) - User keys are stored in KV

# KV Namespace Binding
# Create a KV namespace in your Cloudflare dashboard (Workers & Pages > KV)
# and add the binding here.
# [[kv_namespaces]]
# binding = "USER_DATA" # Name used to access the KV namespace in the worker code
# id = "<your_kv_namespace_id>" # The ID of your KV namespace
# preview_id = "<your_kv_namespace_preview_id>" # The Preview ID of your KV namespace
